### ISSUE TITLE
Not sure if it's doing what it should be

### ISSUE THREAD

**Issue by digisavvy** [gaving/gulp-phpcbf#1]
Hey there,
Thanks for doing this; it's pretty cool. =)

So I'm using this for a WordPress project. When I run this task it completes; however, no changes are made, even though, PHPCS reports code issues. If I uncomment the gulp.dest stream, the files are sent to the src folder that are defined within the phpSource variable I set. So it seems like it's doing mostly what it should; but I don't see it fixing anything. Thoughts? I noted this with the Standard from your config and also the 'WordPress' config option set as well.

```
gulp.task('phpcbf', function () {
  return gulp.src( phpSource)
  .pipe(phpcbf({
    bin: vendors+'composer/bin/phpcbf',
    standard: 'WordPress',
    warningSeverity: 0
  }))
  .on('error', gutil.log)
    .pipe( notify( { message: 'phpcs task complete', onLast: true } ) )
    // .pipe(gulp.dest('src'));
});
```

**Comment by gaving** [comment]
Hi there!

Is that `bin` path definitely correct? Does it work if you were to try changing the standard to a built in one (e.g. `PEAR` or `PSR2`?)

I've noticed the error output could be better, I'll need to try and sort that.

**Comment by digisavvy** [comment]
Thanks for the speedy reply! I did confirm the path is correct, also tried changing out standards and still the same thing. The task DOES actually run, so it does what it thinks it needs to, but none of the files are touched/modified. Even when allowing the files to be copied to the src folder I ran a diff and no changes were found. Running phpcbf by itself does work, fwiw; just within the task is where there seems to be an issue.

**Comment by gaving** [comment]
Hey, not forgotten the issues you're having but struggling to reproduce it!

Could you try the following:

```
git clone https://gist.github.com/gaving/83a421d1fc5dc4c409e4 gulp-phpcbf-test && cd $_
npm install
gulp
git diff
```

Hopefully when you do the last `git diff` you'll see the file `test.php` has been modified with the style changes.

**Comment by gaving** [comment]
If you're still having issues give me a shout and I'll re-open this.

**Comment by MatTeague** [comment]
Hi, I'm also having the same issue. If I run `phpcbf --standard=WordPress 404.php` it works and fixes the issues. My task is:

```js
export const wpcs = () => {
	return src(['./**/*.php', '!./config/plugins/**/*'])
		.pipe($.phpcbf({
			bin: '../../vendor/bin/phpcbf',
			standard: 'WordPress',
			warningSeverity: 0
		}))
		.on('error', handleErrors)
		.pipe(dest('./'));
};
```
I've creatested a dulpicate task with gulp-phpcs 

```js
export const wpcs = () => {
	return src(['./**/*.php', '!./config/plugins/**/*'])
		.pipe($.phpcs({
			bin: '../../vendor/bin/phpcs',
			standard: 'WordPress',
			warningSeverity: 0
		}))
		.on('error', handleErrors)
		.pipe(dest('./'));
};
```
and it works but gulp-phpcbf doesn't seem to change any files. Any help you could provide would be great. However, thanks for developing this plugin it's a great idea and hope I can get it to work.
