### ISSUE TITLE
Need 'maxBuffer' option

### ISSUE THREAD

**Issue by egalpin** [gaving/gulp-phpcbf#2]
Hi there,

Awesome tool, making good use of it so far. Thanks for you efforts.

I've noticed that on large code bases, the following error is logged and the files not 'fixed' as a result:
{ [Error: stdout maxBuffer exceeded.]
  name: 'Error',
  message: **'stdout maxBuffer exceeded.'**,
  stack: 'Error: stdout maxBuffer exceeded.\n    at Socket.<anonymous> (child_process.js:699:13)\n    at Socket.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:765:14)\n    at Socket.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:427:10)\n    at emitReadable (_stream_readable.js:423:5)\n    at readableAddChunk (_stream_readable.js:166:9)\n    at Socket.Readable.push (_stream_readable.js:128:10)\n    at Pipe.onread (net.js:529:21)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-phpcbf' }

Is there a way to set 'maxBuffer' through your tool's settings? If not, consider it a feature request!

Thanks again.

**Comment by egalpin** [comment]
Might there be a way to pass through configuration options and their values to phpcbf?

**Comment by gaving** [comment]
Hi there - 

I've just pushed 0.1.2 which should ignore the `maxBuffer` option and sort this.

Let me know how you get on (obviously it will keep consuming memory up to the file size of the files!)

**Comment by egalpin** [comment]
Fixed the maxBuffer error that I was having. Thanks
