### ISSUE TITLE
gulp watch

### ISSUE THREAD

**Issue by helgenlechner** [gaving/gulp-phpcbf#3]
Hi! This is a really great package, very handy!

I'm running into a problem when trying to use this with gulp watch. Basically, gulp-phpcbf retriggers itself when writing out the changed files, so it just keeps running again and again. Do you have any ideas on how to be able to utilize phpcbf with gulp watch?

Here's my relevant code:

``` javascript
gulp.task('phpcbf', function() {
    return gulp.src('app/**/*.php')
        .pipe(phpcbf({
            bin: 'phpcbf',
            standard: 'PSR2',
            warningSeverity: 0
        })
        .pipe(gulp.dest('app'));
});

gulp.task('watch', function() {
    gulp.watch('app/**/*.php', ['phpcbf']);
});
```

Thanks!

**Comment by gaving** [comment]
Hi there, glad you find it useful!

Interestingly I couldn't re-produce an infinite loop like that (tried both built-in `gulp.watch` and `gulp-watch`) but I did get the task triggering a random amount of times when saving in a watched directory.

If I get some time this week I'll try and see what's up, was going to try throwing [gulp-cached](https://github.com/wearefractal/gulp-cached) in and see if it made a difference.

**Comment by helgenlechner** [comment]
Thanks! I added gulp-cached to my task and it now only runs twice on the first save, and once thereafter. That's not bad.
